TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.cpp \
    pjproject-2.7.2/pjlib/src/pj/addr_resolv_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/exception_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_uwp.cpp \
    pjproject-2.7.2/pjlib/src/pj/ip_helper_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/log_writer_symbian_console.cpp \
    pjproject-2.7.2/pjlib/src/pj/os_core_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/os_error_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/os_info_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/pool_policy_new.cpp \
    pjproject-2.7.2/pjlib/src/pj/sock_qos_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/sock_select_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/sock_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/sock_uwp.cpp \
    pjproject-2.7.2/pjlib/src/pj/ssl_sock_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/timer_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pj/unicode_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pjlib++-test/main.cpp \
    pjproject-2.7.2/pjlib/src/pjlib-test/exception_wrap.cpp \
    pjproject-2.7.2/pjlib/src/pjlib-test/main_symbian.cpp \
    pjproject-2.7.2/pjlib/src/pjlib-test/pool_wrap.cpp \
    pjproject-2.7.2/pjlib/src/pjlib-test/test_wrap.cpp \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/resolver_wrap.cpp \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/xml_wrap.cpp \
    pjproject-2.7.2/pjmedia/src/pjmedia/sdp_wrap.cpp \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/symb_aps_dev.cpp \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/symb_mda_dev.cpp \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/symb_vas_dev.cpp \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/wasapi_dev.cpp \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/openh264.cpp \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/dshowclasses.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_auth_parser_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_dialog_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_endpoint_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_parser_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_tel_uri_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_transport_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_util_proxy_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsip/sip_util_wrap.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/account.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/call.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/endpoint.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/json.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/media.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/persistent.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/presence.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/siptypes.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2/types.cpp \
    pjproject-2.7.2/pjsip/src/pjsua2-test/main.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/android/jni/pjsua_app_callback.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/bb10/src/applicationui.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/bb10/src/main.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/src/pjsuaApplication.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/src/pjsuaAppUi.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/src/pjsuaContainer.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/src/PjsuaContainerView.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/src/pjsuaDocument.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/cli/comp/src/Globals.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/cli/comp/src/PjsuaCallback.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipBackEnd/ApiLock.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipBackEnd/MyApp.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipBackEnd/pch.cpp \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipHost/VoipHost.cpp \
    pjproject-2.7.2/pjsip-apps/src/samples/debug.cpp \
    pjproject-2.7.2/pjsip-apps/src/samples/pjsua2_demo.cpp \
    pjproject-2.7.2/pjsip-apps/src/symsndtest/app_main.cpp \
    pjproject-2.7.2/pjsip-apps/src/symsndtest/main_symbian.cpp \
    pjproject-2.7.2/pjsip-apps/src/vidgui/vidgui.cpp \
    pjproject-2.7.2/pjsip-apps/src/vidgui/vidwin.cpp \
    pjproject-2.7.2/third_party/BaseClasses/amfilter.cpp \
    pjproject-2.7.2/third_party/BaseClasses/amvideo.cpp \
    pjproject-2.7.2/third_party/BaseClasses/arithutil.cpp \
    pjproject-2.7.2/third_party/BaseClasses/combase.cpp \
    pjproject-2.7.2/third_party/BaseClasses/ctlutil.cpp \
    pjproject-2.7.2/third_party/BaseClasses/mtype.cpp \
    pjproject-2.7.2/third_party/BaseClasses/renbase.cpp \
    pjproject-2.7.2/third_party/BaseClasses/wxdebug.cpp \
    pjproject-2.7.2/third_party/BaseClasses/wxlist.cpp \
    pjproject-2.7.2/third_party/BaseClasses/wxutil.cpp \
    pjproject-2.7.2/third_party/threademulation/src/ThreadEmulation.cpp \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/real_fft_unittest.cc \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/signal_processing_unittest.cc \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/echo_cancellation_unittest.cc \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/system_delay_unittest.cc \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/logging/aec_logging_file_handling.cc \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/utility/delay_estimator_unittest.cc \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/system_wrappers/source/cpu_features.cc \
    pjproject-2.7.2/third_party/yuv/source/compare.cc \
    pjproject-2.7.2/third_party/yuv/source/compare_common.cc \
    pjproject-2.7.2/third_party/yuv/source/compare_gcc.cc \
    pjproject-2.7.2/third_party/yuv/source/compare_neon.cc \
    pjproject-2.7.2/third_party/yuv/source/compare_neon64.cc \
    pjproject-2.7.2/third_party/yuv/source/compare_win.cc \
    pjproject-2.7.2/third_party/yuv/source/convert.cc \
    pjproject-2.7.2/third_party/yuv/source/convert_argb.cc \
    pjproject-2.7.2/third_party/yuv/source/convert_from.cc \
    pjproject-2.7.2/third_party/yuv/source/convert_from_argb.cc \
    pjproject-2.7.2/third_party/yuv/source/convert_jpeg.cc \
    pjproject-2.7.2/third_party/yuv/source/convert_to_argb.cc \
    pjproject-2.7.2/third_party/yuv/source/convert_to_i420.cc \
    pjproject-2.7.2/third_party/yuv/source/cpu_id.cc \
    pjproject-2.7.2/third_party/yuv/source/mjpeg_decoder.cc \
    pjproject-2.7.2/third_party/yuv/source/mjpeg_validate.cc \
    pjproject-2.7.2/third_party/yuv/source/planar_functions.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_any.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_argb.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_common.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_dspr2.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_gcc.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_msa.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_neon.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_neon64.cc \
    pjproject-2.7.2/third_party/yuv/source/rotate_win.cc \
    pjproject-2.7.2/third_party/yuv/source/row_any.cc \
    pjproject-2.7.2/third_party/yuv/source/row_common.cc \
    pjproject-2.7.2/third_party/yuv/source/row_dspr2.cc \
    pjproject-2.7.2/third_party/yuv/source/row_gcc.cc \
    pjproject-2.7.2/third_party/yuv/source/row_msa.cc \
    pjproject-2.7.2/third_party/yuv/source/row_neon.cc \
    pjproject-2.7.2/third_party/yuv/source/row_neon64.cc \
    pjproject-2.7.2/third_party/yuv/source/row_win.cc \
    pjproject-2.7.2/third_party/yuv/source/scale.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_any.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_argb.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_common.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_dspr2.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_gcc.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_msa.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_neon.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_neon64.cc \
    pjproject-2.7.2/third_party/yuv/source/scale_win.cc \
    pjproject-2.7.2/third_party/yuv/source/video_common.cc \
    pjproject-2.7.2/pjlib/src/pj/compat/sigjmp.c \
    pjproject-2.7.2/pjlib/src/pj/compat/string.c \
    pjproject-2.7.2/pjlib/src/pj/compat/string_compat.c \
    pjproject-2.7.2/pjlib/src/pj/activesock.c \
    pjproject-2.7.2/pjlib/src/pj/addr_resolv_linux_kernel.c \
    pjproject-2.7.2/pjlib/src/pj/addr_resolv_sock.c \
    pjproject-2.7.2/pjlib/src/pj/array.c \
    pjproject-2.7.2/pjlib/src/pj/config.c \
    pjproject-2.7.2/pjlib/src/pj/ctype.c \
    pjproject-2.7.2/pjlib/src/pj/errno.c \
    pjproject-2.7.2/pjlib/src/pj/except.c \
    pjproject-2.7.2/pjlib/src/pj/extra-exports.c \
    pjproject-2.7.2/pjlib/src/pj/fifobuf.c \
    pjproject-2.7.2/pjlib/src/pj/file_access_unistd.c \
    pjproject-2.7.2/pjlib/src/pj/file_access_win32.c \
    pjproject-2.7.2/pjlib/src/pj/file_io_ansi.c \
    pjproject-2.7.2/pjlib/src/pj/file_io_win32.c \
    pjproject-2.7.2/pjlib/src/pj/guid.c \
    pjproject-2.7.2/pjlib/src/pj/guid_android.c \
    pjproject-2.7.2/pjlib/src/pj/guid_simple.c \
    pjproject-2.7.2/pjlib/src/pj/guid_uuid.c \
    pjproject-2.7.2/pjlib/src/pj/guid_win32.c \
    pjproject-2.7.2/pjlib/src/pj/hash.c \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_common_abs.c \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_dummy.c \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_epoll.c \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_linux_kernel.c \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_select.c \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_winnt.c \
    pjproject-2.7.2/pjlib/src/pj/ip_helper_generic.c \
    pjproject-2.7.2/pjlib/src/pj/ip_helper_win32.c \
    pjproject-2.7.2/pjlib/src/pj/ip_helper_winphone8.c \
    pjproject-2.7.2/pjlib/src/pj/list.c \
    pjproject-2.7.2/pjlib/src/pj/lock.c \
    pjproject-2.7.2/pjlib/src/pj/log.c \
    pjproject-2.7.2/pjlib/src/pj/log_writer_printk.c \
    pjproject-2.7.2/pjlib/src/pj/log_writer_stdout.c \
    pjproject-2.7.2/pjlib/src/pj/os_core_linux_kernel.c \
    pjproject-2.7.2/pjlib/src/pj/os_core_unix.c \
    pjproject-2.7.2/pjlib/src/pj/os_core_win32.c \
    pjproject-2.7.2/pjlib/src/pj/os_error_linux_kernel.c \
    pjproject-2.7.2/pjlib/src/pj/os_error_unix.c \
    pjproject-2.7.2/pjlib/src/pj/os_error_win32.c \
    pjproject-2.7.2/pjlib/src/pj/os_info.c \
    pjproject-2.7.2/pjlib/src/pj/os_rwmutex.c \
    pjproject-2.7.2/pjlib/src/pj/os_time_bsd.c \
    pjproject-2.7.2/pjlib/src/pj/os_time_common.c \
    pjproject-2.7.2/pjlib/src/pj/os_time_linux_kernel.c \
    pjproject-2.7.2/pjlib/src/pj/os_time_unix.c \
    pjproject-2.7.2/pjlib/src/pj/os_time_win32.c \
    pjproject-2.7.2/pjlib/src/pj/os_timestamp_common.c \
    pjproject-2.7.2/pjlib/src/pj/os_timestamp_linux_kernel.c \
    pjproject-2.7.2/pjlib/src/pj/os_timestamp_posix.c \
    pjproject-2.7.2/pjlib/src/pj/os_timestamp_win32.c \
    pjproject-2.7.2/pjlib/src/pj/pool.c \
    pjproject-2.7.2/pjlib/src/pj/pool_buf.c \
    pjproject-2.7.2/pjlib/src/pj/pool_caching.c \
    pjproject-2.7.2/pjlib/src/pj/pool_dbg.c \
    pjproject-2.7.2/pjlib/src/pj/pool_policy_kmalloc.c \
    pjproject-2.7.2/pjlib/src/pj/pool_policy_malloc.c \
    pjproject-2.7.2/pjlib/src/pj/rand.c \
    pjproject-2.7.2/pjlib/src/pj/rbtree.c \
    pjproject-2.7.2/pjlib/src/pj/sock_bsd.c \
    pjproject-2.7.2/pjlib/src/pj/sock_common.c \
    pjproject-2.7.2/pjlib/src/pj/sock_linux_kernel.c \
    pjproject-2.7.2/pjlib/src/pj/sock_qos_bsd.c \
    pjproject-2.7.2/pjlib/src/pj/sock_qos_common.c \
    pjproject-2.7.2/pjlib/src/pj/sock_qos_darwin.c \
    pjproject-2.7.2/pjlib/src/pj/sock_qos_dummy.c \
    pjproject-2.7.2/pjlib/src/pj/sock_qos_wm.c \
    pjproject-2.7.2/pjlib/src/pj/sock_select.c \
    pjproject-2.7.2/pjlib/src/pj/ssl_sock_common.c \
    pjproject-2.7.2/pjlib/src/pj/ssl_sock_dump.c \
    pjproject-2.7.2/pjlib/src/pj/ssl_sock_ossl.c \
    pjproject-2.7.2/pjlib/src/pj/string.c \
    pjproject-2.7.2/pjlib/src/pj/symbols.c \
    pjproject-2.7.2/pjlib/src/pj/timer.c \
    pjproject-2.7.2/pjlib/src/pj/types.c \
    pjproject-2.7.2/pjlib/src/pj/unicode_win32.c \
    pjproject-2.7.2/pjlib/src/pjlib-samples/except.c \
    pjproject-2.7.2/pjlib/src/pjlib-samples/list.c \
    pjproject-2.7.2/pjlib/src/pjlib-samples/log.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/activesock.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/atomic.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/echo_clt.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/errno.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/exception.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/fifobuf.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/file.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/hash_test.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/ioq_perf.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/ioq_tcp.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/ioq_udp.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/ioq_unreg.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/list.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/main.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/main_mod.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/main_rtems.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/main_win32.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/mutex.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/os.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/pool.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/pool_perf.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/rand.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/rbtree.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/select.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/sleep.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/sock.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/sock_perf.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/ssl_sock.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/string.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/test.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/thread.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/timer.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/timestamp.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/udp_echo_srv_ioqueue.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/udp_echo_srv_sync.c \
    pjproject-2.7.2/pjlib/src/pjlib-test/util.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/base64.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/cli.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/cli_console.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/cli_telnet.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/crc32.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/dns.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/dns_dump.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/dns_server.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/errno.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/getopt.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/hmac_md5.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/hmac_sha1.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/http_client.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/json.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/md5.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/pcap.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/resolver.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/scanner.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/scanner_cis_bitwise.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/scanner_cis_uint.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/sha1.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/srv_resolver.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/string.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/stun_simple.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/stun_simple_client.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/symbols.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util/xml.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/encryption.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/http_client.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/json_test.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/main.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/main_rtems.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/main_win32.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/resolver_test.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/stun.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/test.c \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/xml.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/alaw_ulaw.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/alaw_ulaw_table.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/audiodev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/avi_player.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/bidirectional.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/clock_thread.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/codec.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/conf_switch.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/conference.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/converter.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/converter_libswscale.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/converter_libyuv.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/delaybuf.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/dummy.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/echo_common.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/echo_port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/echo_speex.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/echo_suppress.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/echo_webrtc.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/endpoint.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/errno.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/event.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/ffmpeg_util.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/format.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/g711.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/jbuf.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/master_port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/mem_capture.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/mem_player.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/null_port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/plc_common.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/resample_libsamplerate.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/resample_port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/resample_resample.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/resample_speex.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/rtcp.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/rtcp_xr.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/rtp.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/sdp.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/sdp_cmp.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/sdp_neg.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/session.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/silencedet.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/sound_legacy.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/sound_port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/splitcomb.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/stereo_port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/stream.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/stream_common.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/stream_info.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/tonegen.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/transport_adapter_sample.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/transport_ice.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/transport_loop.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/transport_srtp.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/transport_srtp_dtls.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/transport_srtp_sdes.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/transport_udp.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/types.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/vid_codec.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/vid_codec_util.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/vid_port.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/vid_stream.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/vid_stream_info.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/vid_tee.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/videodev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/wav_player.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/wav_playlist.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/wav_writer.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/wave.c \
    pjproject-2.7.2/pjmedia/src/pjmedia/wsola.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/alsa_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/android_jni_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/audiodev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/audiotest.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/bb10_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/bdimad_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/errno.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/legacy_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/null_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/opensl_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/pa_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/wmme_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/g722/g722_dec.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/g722/g722_enc.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/amr_sdp_match.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/audio_codecs.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/bcg729.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/ffmpeg_vid_codecs.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/g722.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/g7221.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/g7221_sdp_match.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/gsm.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/h263_packetizer.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/h264_packetizer.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/ilbc.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/ipp_codecs.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/l16.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/opencore_amr.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/opus.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/passthrough.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/silk.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/speex_codec.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/android_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/android_opengl.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/avi_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/colorbar_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/dshow_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/errno.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/ffmpeg_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/opengl_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/sdl_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/util.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/v4l2_dev.c \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/videodev.c \
    pjproject-2.7.2/pjmedia/src/test/audio_tool.c \
    pjproject-2.7.2/pjmedia/src/test/codec_vectors.c \
    pjproject-2.7.2/pjmedia/src/test/jbuf_test.c \
    pjproject-2.7.2/pjmedia/src/test/main.c \
    pjproject-2.7.2/pjmedia/src/test/mips_test.c \
    pjproject-2.7.2/pjmedia/src/test/rtp_test.c \
    pjproject-2.7.2/pjmedia/src/test/sdp_neg_test.c \
    pjproject-2.7.2/pjmedia/src/test/sdptest.c \
    pjproject-2.7.2/pjmedia/src/test/session_test.c \
    pjproject-2.7.2/pjmedia/src/test/test.c \
    pjproject-2.7.2/pjmedia/src/test/vid_codec_test.c \
    pjproject-2.7.2/pjmedia/src/test/vid_dev_test.c \
    pjproject-2.7.2/pjmedia/src/test/vid_port_test.c \
    pjproject-2.7.2/pjmedia/src/test/wince_main.c \
    pjproject-2.7.2/pjmedia/src/test/wsola_test.c \
    pjproject-2.7.2/pjnath/src/pjnath/errno.c \
    pjproject-2.7.2/pjnath/src/pjnath/ice_session.c \
    pjproject-2.7.2/pjnath/src/pjnath/ice_strans.c \
    pjproject-2.7.2/pjnath/src/pjnath/nat_detect.c \
    pjproject-2.7.2/pjnath/src/pjnath/stun_auth.c \
    pjproject-2.7.2/pjnath/src/pjnath/stun_msg.c \
    pjproject-2.7.2/pjnath/src/pjnath/stun_msg_dump.c \
    pjproject-2.7.2/pjnath/src/pjnath/stun_session.c \
    pjproject-2.7.2/pjnath/src/pjnath/stun_sock.c \
    pjproject-2.7.2/pjnath/src/pjnath/stun_transaction.c \
    pjproject-2.7.2/pjnath/src/pjnath/turn_session.c \
    pjproject-2.7.2/pjnath/src/pjnath/turn_sock.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/concur_test.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/ice_test.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/main.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/main_win32.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/server.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/sess_auth.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/stun.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/stun_sock_test.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/test.c \
    pjproject-2.7.2/pjnath/src/pjnath-test/turn_sock_test.c \
    pjproject-2.7.2/pjnath/src/pjturn-client/client_main.c \
    pjproject-2.7.2/pjnath/src/pjturn-srv/allocation.c \
    pjproject-2.7.2/pjnath/src/pjturn-srv/auth.c \
    pjproject-2.7.2/pjnath/src/pjturn-srv/listener_tcp.c \
    pjproject-2.7.2/pjnath/src/pjturn-srv/listener_udp.c \
    pjproject-2.7.2/pjnath/src/pjturn-srv/main.c \
    pjproject-2.7.2/pjnath/src/pjturn-srv/server.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_auth_aka.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_auth_client.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_auth_msg.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_auth_parser.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_auth_server.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_config.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_dialog.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_endpoint.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_errno.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_msg.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_multipart.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_parser.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_resolve.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_tel_uri.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_transaction.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_transport.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_transport_loop.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_transport_tcp.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_transport_tls.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_transport_udp.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_ua_layer.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_uri.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_util.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_util_proxy.c \
    pjproject-2.7.2/pjsip/src/pjsip/sip_util_statefull.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/errno.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/evsub.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/evsub_msg.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/iscomposing.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/mwi.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/pidf.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/presence.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/presence_body.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/publishc.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/rpid.c \
    pjproject-2.7.2/pjsip/src/pjsip-simple/xpidf.c \
    pjproject-2.7.2/pjsip/src/pjsip-ua/sip_100rel.c \
    pjproject-2.7.2/pjsip/src/pjsip-ua/sip_inv.c \
    pjproject-2.7.2/pjsip/src/pjsip-ua/sip_reg.c \
    pjproject-2.7.2/pjsip/src/pjsip-ua/sip_replaces.c \
    pjproject-2.7.2/pjsip/src/pjsip-ua/sip_timer.c \
    pjproject-2.7.2/pjsip/src/pjsip-ua/sip_xfer.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_acc.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_aud.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_call.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_core.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_dump.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_im.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_media.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_pres.c \
    pjproject-2.7.2/pjsip/src/pjsua-lib/pjsua_vid.c \
    pjproject-2.7.2/pjsip/src/test/dlg_core_test.c \
    pjproject-2.7.2/pjsip/src/test/dns_test.c \
    pjproject-2.7.2/pjsip/src/test/inv_offer_answer_test.c \
    pjproject-2.7.2/pjsip/src/test/main.c \
    pjproject-2.7.2/pjsip/src/test/main_rtems.c \
    pjproject-2.7.2/pjsip/src/test/main_win32.c \
    pjproject-2.7.2/pjsip/src/test/msg_err_test.c \
    pjproject-2.7.2/pjsip/src/test/msg_logger.c \
    pjproject-2.7.2/pjsip/src/test/msg_test.c \
    pjproject-2.7.2/pjsip/src/test/multipart_test.c \
    pjproject-2.7.2/pjsip/src/test/regc_test.c \
    pjproject-2.7.2/pjsip/src/test/test.c \
    pjproject-2.7.2/pjsip/src/test/transport_loop_test.c \
    pjproject-2.7.2/pjsip/src/test/transport_tcp_test.c \
    pjproject-2.7.2/pjsip/src/test/transport_test.c \
    pjproject-2.7.2/pjsip/src/test/transport_udp_test.c \
    pjproject-2.7.2/pjsip/src/test/tsx_basic_test.c \
    pjproject-2.7.2/pjsip/src/test/tsx_bench.c \
    pjproject-2.7.2/pjsip/src/test/tsx_uac_test.c \
    pjproject-2.7.2/pjsip/src/test/tsx_uas_test.c \
    pjproject-2.7.2/pjsip/src/test/txdata_test.c \
    pjproject-2.7.2/pjsip/src/test/uri_test.c \
    pjproject-2.7.2/pjsip-apps/build/dummy.c \
    pjproject-2.7.2/pjsip-apps/src/3rdparty_media_sample/alt_pjsua_aud.c \
    pjproject-2.7.2/pjsip-apps/src/3rdparty_media_sample/alt_pjsua_vid.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/wm/main_wm.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/main.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/main_rtems.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app_cli.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app_common.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app_config.c \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app_legacy.c \
    pjproject-2.7.2/pjsip-apps/src/pjsystest/main_console.c \
    pjproject-2.7.2/pjsip-apps/src/pjsystest/main_wm.c \
    pjproject-2.7.2/pjsip-apps/src/pjsystest/systest.c \
    pjproject-2.7.2/pjsip-apps/src/py_pjsua/py_pjsua.c \
    pjproject-2.7.2/pjsip-apps/src/python/_pjsua.c \
    pjproject-2.7.2/pjsip-apps/src/samples/android_sample/jni/dummy.c \
    pjproject-2.7.2/pjsip-apps/src/samples/aectest.c \
    pjproject-2.7.2/pjsip-apps/src/samples/auddemo.c \
    pjproject-2.7.2/pjsip-apps/src/samples/aviplay.c \
    pjproject-2.7.2/pjsip-apps/src/samples/cl_pjsua_demo.c \
    pjproject-2.7.2/pjsip-apps/src/samples/clidemo.c \
    pjproject-2.7.2/pjsip-apps/src/samples/confbench.c \
    pjproject-2.7.2/pjsip-apps/src/samples/confsample.c \
    pjproject-2.7.2/pjsip-apps/src/samples/encdec.c \
    pjproject-2.7.2/pjsip-apps/src/samples/footprint.c \
    pjproject-2.7.2/pjsip-apps/src/samples/httpdemo.c \
    pjproject-2.7.2/pjsip-apps/src/samples/icedemo.c \
    pjproject-2.7.2/pjsip-apps/src/samples/invtester.c \
    pjproject-2.7.2/pjsip-apps/src/samples/jbsim.c \
    pjproject-2.7.2/pjsip-apps/src/samples/latency.c \
    pjproject-2.7.2/pjsip-apps/src/samples/level.c \
    pjproject-2.7.2/pjsip-apps/src/samples/main_rtems.c \
    pjproject-2.7.2/pjsip-apps/src/samples/mix.c \
    pjproject-2.7.2/pjsip-apps/src/samples/pcaputil.c \
    pjproject-2.7.2/pjsip-apps/src/samples/pjsip-perf.c \
    pjproject-2.7.2/pjsip-apps/src/samples/playfile.c \
    pjproject-2.7.2/pjsip-apps/src/samples/playsine.c \
    pjproject-2.7.2/pjsip-apps/src/samples/recfile.c \
    pjproject-2.7.2/pjsip-apps/src/samples/resampleplay.c \
    pjproject-2.7.2/pjsip-apps/src/samples/simple_pjsua.c \
    pjproject-2.7.2/pjsip-apps/src/samples/simpleua.c \
    pjproject-2.7.2/pjsip-apps/src/samples/sipecho.c \
    pjproject-2.7.2/pjsip-apps/src/samples/siprtp.c \
    pjproject-2.7.2/pjsip-apps/src/samples/siprtp_report.c \
    pjproject-2.7.2/pjsip-apps/src/samples/sipstateless.c \
    pjproject-2.7.2/pjsip-apps/src/samples/stateful_proxy.c \
    pjproject-2.7.2/pjsip-apps/src/samples/stateless_proxy.c \
    pjproject-2.7.2/pjsip-apps/src/samples/stereotest.c \
    pjproject-2.7.2/pjsip-apps/src/samples/streamutil.c \
    pjproject-2.7.2/pjsip-apps/src/samples/strerror.c \
    pjproject-2.7.2/pjsip-apps/src/samples/tonegen.c \
    pjproject-2.7.2/pjsip-apps/src/samples/vid_codec_test.c \
    pjproject-2.7.2/pjsip-apps/src/samples/vid_streamutil.c \
    pjproject-2.7.2/pjsip-apps/src/swig/python/cc_mingw.c \
    pjproject-2.7.2/tests/pjsua/tools/cmp_wav.c \
    pjproject-2.7.2/third_party/g7221/common/basic_op.c \
    pjproject-2.7.2/third_party/g7221/common/common.c \
    pjproject-2.7.2/third_party/g7221/common/huff_tab.c \
    pjproject-2.7.2/third_party/g7221/common/tables.c \
    pjproject-2.7.2/third_party/g7221/decode/coef2sam.c \
    pjproject-2.7.2/third_party/g7221/decode/dct4_s.c \
    pjproject-2.7.2/third_party/g7221/decode/decoder.c \
    pjproject-2.7.2/third_party/g7221/encode/dct4_a.c \
    pjproject-2.7.2/third_party/g7221/encode/encoder.c \
    pjproject-2.7.2/third_party/g7221/encode/sam2coef.c \
    pjproject-2.7.2/third_party/gsm/add-test/add_test.c \
    pjproject-2.7.2/third_party/gsm/src/add.c \
    pjproject-2.7.2/third_party/gsm/src/code.c \
    pjproject-2.7.2/third_party/gsm/src/debug.c \
    pjproject-2.7.2/third_party/gsm/src/decode.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_create.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_decode.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_destroy.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_encode.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_explode.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_implode.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_option.c \
    pjproject-2.7.2/third_party/gsm/src/gsm_print.c \
    pjproject-2.7.2/third_party/gsm/src/long_term.c \
    pjproject-2.7.2/third_party/gsm/src/lpc.c \
    pjproject-2.7.2/third_party/gsm/src/preprocess.c \
    pjproject-2.7.2/third_party/gsm/src/rpe.c \
    pjproject-2.7.2/third_party/gsm/src/short_term.c \
    pjproject-2.7.2/third_party/gsm/src/table.c \
    pjproject-2.7.2/third_party/gsm/src/toast.c \
    pjproject-2.7.2/third_party/gsm/src/toast_alaw.c \
    pjproject-2.7.2/third_party/gsm/src/toast_audio.c \
    pjproject-2.7.2/third_party/gsm/src/toast_lin.c \
    pjproject-2.7.2/third_party/gsm/src/toast_ulaw.c \
    pjproject-2.7.2/third_party/gsm/tls/bitter.c \
    pjproject-2.7.2/third_party/gsm/tls/ginger.c \
    pjproject-2.7.2/third_party/gsm/tls/sour.c \
    pjproject-2.7.2/third_party/gsm/tls/sweet.c \
    pjproject-2.7.2/third_party/gsm/tls/taste.c \
    pjproject-2.7.2/third_party/gsm/tst/cod2lin.c \
    pjproject-2.7.2/third_party/gsm/tst/cod2txt.c \
    pjproject-2.7.2/third_party/gsm/tst/gsm2cod.c \
    pjproject-2.7.2/third_party/gsm/tst/lin2cod.c \
    pjproject-2.7.2/third_party/gsm/tst/lin2txt.c \
    pjproject-2.7.2/third_party/ilbc/anaFilter.c \
    pjproject-2.7.2/third_party/ilbc/constants.c \
    pjproject-2.7.2/third_party/ilbc/createCB.c \
    pjproject-2.7.2/third_party/ilbc/doCPLC.c \
    pjproject-2.7.2/third_party/ilbc/enhancer.c \
    pjproject-2.7.2/third_party/ilbc/filter.c \
    pjproject-2.7.2/third_party/ilbc/FrameClassify.c \
    pjproject-2.7.2/third_party/ilbc/gainquant.c \
    pjproject-2.7.2/third_party/ilbc/getCBvec.c \
    pjproject-2.7.2/third_party/ilbc/helpfun.c \
    pjproject-2.7.2/third_party/ilbc/hpInput.c \
    pjproject-2.7.2/third_party/ilbc/hpOutput.c \
    pjproject-2.7.2/third_party/ilbc/iCBConstruct.c \
    pjproject-2.7.2/third_party/ilbc/iCBSearch.c \
    pjproject-2.7.2/third_party/ilbc/iLBC_decode.c \
    pjproject-2.7.2/third_party/ilbc/iLBC_encode.c \
    pjproject-2.7.2/third_party/ilbc/iLBC_test.c \
    pjproject-2.7.2/third_party/ilbc/LPCdecode.c \
    pjproject-2.7.2/third_party/ilbc/LPCencode.c \
    pjproject-2.7.2/third_party/ilbc/lsf.c \
    pjproject-2.7.2/third_party/ilbc/packing.c \
    pjproject-2.7.2/third_party/ilbc/StateConstructW.c \
    pjproject-2.7.2/third_party/ilbc/StateSearchW.c \
    pjproject-2.7.2/third_party/ilbc/syntFilter.c \
    pjproject-2.7.2/third_party/milenage/milenage.c \
    pjproject-2.7.2/third_party/milenage/rijndael.c \
    pjproject-2.7.2/third_party/mp3/mp3_writer.c \
    pjproject-2.7.2/third_party/resample/src/libresample_dll.c \
    pjproject-2.7.2/third_party/resample/src/resamplesubs.c \
    pjproject-2.7.2/third_party/speex/libspeex/bits.c \
    pjproject-2.7.2/third_party/speex/libspeex/buffer.c \
    pjproject-2.7.2/third_party/speex/libspeex/cb_search.c \
    pjproject-2.7.2/third_party/speex/libspeex/exc_10_16_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/exc_10_32_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/exc_20_32_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/exc_5_256_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/exc_5_64_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/exc_8_128_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/fftwrap.c \
    pjproject-2.7.2/third_party/speex/libspeex/filterbank.c \
    pjproject-2.7.2/third_party/speex/libspeex/filters.c \
    pjproject-2.7.2/third_party/speex/libspeex/gain_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/gain_table_lbr.c \
    pjproject-2.7.2/third_party/speex/libspeex/hexc_10_32_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/hexc_table.c \
    pjproject-2.7.2/third_party/speex/libspeex/high_lsp_tables.c \
    pjproject-2.7.2/third_party/speex/libspeex/jitter.c \
    pjproject-2.7.2/third_party/speex/libspeex/kiss_fft.c \
    pjproject-2.7.2/third_party/speex/libspeex/kiss_fftr.c \
    pjproject-2.7.2/third_party/speex/libspeex/lpc.c \
    pjproject-2.7.2/third_party/speex/libspeex/lsp.c \
    pjproject-2.7.2/third_party/speex/libspeex/lsp_tables_nb.c \
    pjproject-2.7.2/third_party/speex/libspeex/ltp.c \
    pjproject-2.7.2/third_party/speex/libspeex/mdf.c \
    pjproject-2.7.2/third_party/speex/libspeex/modes.c \
    pjproject-2.7.2/third_party/speex/libspeex/modes_wb.c \
    pjproject-2.7.2/third_party/speex/libspeex/nb_celp.c \
    pjproject-2.7.2/third_party/speex/libspeex/preprocess.c \
    pjproject-2.7.2/third_party/speex/libspeex/quant_lsp.c \
    pjproject-2.7.2/third_party/speex/libspeex/resample.c \
    pjproject-2.7.2/third_party/speex/libspeex/sb_celp.c \
    pjproject-2.7.2/third_party/speex/libspeex/scal.c \
    pjproject-2.7.2/third_party/speex/libspeex/smallft.c \
    pjproject-2.7.2/third_party/speex/libspeex/speex.c \
    pjproject-2.7.2/third_party/speex/libspeex/speex_callbacks.c \
    pjproject-2.7.2/third_party/speex/libspeex/speex_header.c \
    pjproject-2.7.2/third_party/speex/libspeex/stereo.c \
    pjproject-2.7.2/third_party/speex/libspeex/testdenoise.c \
    pjproject-2.7.2/third_party/speex/libspeex/testecho.c \
    pjproject-2.7.2/third_party/speex/libspeex/testenc.c \
    pjproject-2.7.2/third_party/speex/libspeex/testenc_uwb.c \
    pjproject-2.7.2/third_party/speex/libspeex/testenc_wb.c \
    pjproject-2.7.2/third_party/speex/libspeex/testjitter.c \
    pjproject-2.7.2/third_party/speex/libspeex/testresample.c \
    pjproject-2.7.2/third_party/speex/libspeex/vbr.c \
    pjproject-2.7.2/third_party/speex/libspeex/vorbis_psy.c \
    pjproject-2.7.2/third_party/speex/libspeex/vq.c \
    pjproject-2.7.2/third_party/speex/libspeex/window.c \
    pjproject-2.7.2/third_party/srtp/crypto/cipher/aes.c \
    pjproject-2.7.2/third_party/srtp/crypto/cipher/aes_gcm_ossl.c \
    pjproject-2.7.2/third_party/srtp/crypto/cipher/aes_icm.c \
    pjproject-2.7.2/third_party/srtp/crypto/cipher/aes_icm_ossl.c \
    pjproject-2.7.2/third_party/srtp/crypto/cipher/cipher.c \
    pjproject-2.7.2/third_party/srtp/crypto/cipher/null_cipher.c \
    pjproject-2.7.2/third_party/srtp/crypto/hash/auth.c \
    pjproject-2.7.2/third_party/srtp/crypto/hash/hmac.c \
    pjproject-2.7.2/third_party/srtp/crypto/hash/hmac_ossl.c \
    pjproject-2.7.2/third_party/srtp/crypto/hash/null_auth.c \
    pjproject-2.7.2/third_party/srtp/crypto/hash/sha1.c \
    pjproject-2.7.2/third_party/srtp/crypto/kernel/alloc.c \
    pjproject-2.7.2/third_party/srtp/crypto/kernel/crypto_kernel.c \
    pjproject-2.7.2/third_party/srtp/crypto/kernel/err.c \
    pjproject-2.7.2/third_party/srtp/crypto/kernel/key.c \
    pjproject-2.7.2/third_party/srtp/crypto/math/datatypes.c \
    pjproject-2.7.2/third_party/srtp/crypto/math/stat.c \
    pjproject-2.7.2/third_party/srtp/crypto/replay/rdb.c \
    pjproject-2.7.2/third_party/srtp/crypto/replay/rdbx.c \
    pjproject-2.7.2/third_party/srtp/crypto/replay/ut_sim.c \
    pjproject-2.7.2/third_party/srtp/pjlib/srtp_err.c \
    pjproject-2.7.2/third_party/srtp/srtp/ekt.c \
    pjproject-2.7.2/third_party/srtp/srtp/srtp.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/auto_corr_to_refl_coef.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/auto_correlation.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/complex_bit_reverse.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/complex_bit_reverse_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/complex_fft.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/complex_fft_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/copy_set_operations.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/cross_correlation.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/cross_correlation_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/cross_correlation_neon.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/division_operations.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/dot_product_with_scale.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/downsample_fast.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/downsample_fast_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/downsample_fast_neon.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/energy.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/filter_ar.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/filter_ar_fast_q12.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/filter_ar_fast_q12_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/filter_ma_fast_q12.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/get_hanning_window.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/get_scaling_square.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/ilbc_specific_functions.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/levinson_durbin.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/lpc_to_refl_coef.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/min_max_operations.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/min_max_operations_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/min_max_operations_neon.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/randomization_functions.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/real_fft.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/refl_coef_to_lpc.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/resample.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/resample_48khz.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/resample_by_2.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/resample_by_2_internal.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/resample_by_2_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/resample_fractional.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/spl_init.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/spl_sqrt.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/spl_sqrt_floor.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/spl_sqrt_floor_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/splitting_filter.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/sqrt_of_one_minus_x_squared.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/vector_scaling_operations.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/vector_scaling_operations_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/fft4g.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/ring_buffer.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_core.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_core_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_core_neon.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_core_sse2.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_rdft.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_rdft_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_rdft_neon.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_rdft_sse2.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_resampler.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/echo_cancellation.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/aecm_core.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/aecm_core_c.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/aecm_core_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/aecm_core_neon.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/echo_control_mobile.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/noise_suppression.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/noise_suppression_x.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/ns_core.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/nsx_core.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/nsx_core_c.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/nsx_core_mips.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/nsx_core_neon.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/utility/delay_estimator.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/utility/delay_estimator_wrapper.c \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/system_wrappers/source/cpu_features_android.c \
    pjproject-2.7.2/main.cpp

HEADERS += \
    pjproject-2.7.2/pjlib/include/pj/compat/assert.h \
    pjproject-2.7.2/pjlib/include/pj/compat/cc_armcc.h \
    pjproject-2.7.2/pjlib/include/pj/compat/cc_codew.h \
    pjproject-2.7.2/pjlib/include/pj/compat/cc_gcc.h \
    pjproject-2.7.2/pjlib/include/pj/compat/cc_gcce.h \
    pjproject-2.7.2/pjlib/include/pj/compat/cc_msvc.h \
    pjproject-2.7.2/pjlib/include/pj/compat/cc_mwcc.h \
    pjproject-2.7.2/pjlib/include/pj/compat/ctype.h \
    pjproject-2.7.2/pjlib/include/pj/compat/errno.h \
    pjproject-2.7.2/pjlib/include/pj/compat/high_precision.h \
    pjproject-2.7.2/pjlib/include/pj/compat/limits.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_alpha.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_armv4.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_auto.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_i386.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_m68k.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_powerpc.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_sparc.h \
    pjproject-2.7.2/pjlib/include/pj/compat/m_x86_64.h \
    pjproject-2.7.2/pjlib/include/pj/compat/malloc.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_auto.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_darwinos.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_linux.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_linux_kernel.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_palmos.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_rtems.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_sunos.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_symbian.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_win32.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_win32_wince.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_winphone8.h \
    pjproject-2.7.2/pjlib/include/pj/compat/os_winuwp.h \
    pjproject-2.7.2/pjlib/include/pj/compat/rand.h \
    pjproject-2.7.2/pjlib/include/pj/compat/setjmp.h \
    pjproject-2.7.2/pjlib/include/pj/compat/size_t.h \
    pjproject-2.7.2/pjlib/include/pj/compat/socket.h \
    pjproject-2.7.2/pjlib/include/pj/compat/stdarg.h \
    pjproject-2.7.2/pjlib/include/pj/compat/stdfileio.h \
    pjproject-2.7.2/pjlib/include/pj/compat/string.h \
    pjproject-2.7.2/pjlib/include/pj/compat/time.h \
    pjproject-2.7.2/pjlib/include/pj/activesock.h \
    pjproject-2.7.2/pjlib/include/pj/addr_resolv.h \
    pjproject-2.7.2/pjlib/include/pj/array.h \
    pjproject-2.7.2/pjlib/include/pj/assert.h \
    pjproject-2.7.2/pjlib/include/pj/config.h \
    pjproject-2.7.2/pjlib/include/pj/config_site.h \
    pjproject-2.7.2/pjlib/include/pj/config_site_sample.h \
    pjproject-2.7.2/pjlib/include/pj/ctype.h \
    pjproject-2.7.2/pjlib/include/pj/doxygen.h \
    pjproject-2.7.2/pjlib/include/pj/errno.h \
    pjproject-2.7.2/pjlib/include/pj/except.h \
    pjproject-2.7.2/pjlib/include/pj/fifobuf.h \
    pjproject-2.7.2/pjlib/include/pj/file_access.h \
    pjproject-2.7.2/pjlib/include/pj/file_io.h \
    pjproject-2.7.2/pjlib/include/pj/guid.h \
    pjproject-2.7.2/pjlib/include/pj/hash.h \
    pjproject-2.7.2/pjlib/include/pj/ioqueue.h \
    pjproject-2.7.2/pjlib/include/pj/ip_helper.h \
    pjproject-2.7.2/pjlib/include/pj/limits.h \
    pjproject-2.7.2/pjlib/include/pj/list.h \
    pjproject-2.7.2/pjlib/include/pj/list_i.h \
    pjproject-2.7.2/pjlib/include/pj/lock.h \
    pjproject-2.7.2/pjlib/include/pj/log.h \
    pjproject-2.7.2/pjlib/include/pj/math.h \
    pjproject-2.7.2/pjlib/include/pj/os.h \
    pjproject-2.7.2/pjlib/include/pj/pool.h \
    pjproject-2.7.2/pjlib/include/pj/pool_alt.h \
    pjproject-2.7.2/pjlib/include/pj/pool_buf.h \
    pjproject-2.7.2/pjlib/include/pj/pool_i.h \
    pjproject-2.7.2/pjlib/include/pj/rand.h \
    pjproject-2.7.2/pjlib/include/pj/rbtree.h \
    pjproject-2.7.2/pjlib/include/pj/sock.h \
    pjproject-2.7.2/pjlib/include/pj/sock_qos.h \
    pjproject-2.7.2/pjlib/include/pj/sock_select.h \
    pjproject-2.7.2/pjlib/include/pj/ssl_sock.h \
    pjproject-2.7.2/pjlib/include/pj/string.h \
    pjproject-2.7.2/pjlib/include/pj/string_i.h \
    pjproject-2.7.2/pjlib/include/pj/timer.h \
    pjproject-2.7.2/pjlib/include/pj/types.h \
    pjproject-2.7.2/pjlib/include/pj/unicode.h \
    pjproject-2.7.2/pjlib/include/pj++/file.hpp \
    pjproject-2.7.2/pjlib/include/pj++/hash.hpp \
    pjproject-2.7.2/pjlib/include/pj++/list.hpp \
    pjproject-2.7.2/pjlib/include/pj++/lock.hpp \
    pjproject-2.7.2/pjlib/include/pj++/os.hpp \
    pjproject-2.7.2/pjlib/include/pj++/pool.hpp \
    pjproject-2.7.2/pjlib/include/pj++/proactor.hpp \
    pjproject-2.7.2/pjlib/include/pj++/scanner.hpp \
    pjproject-2.7.2/pjlib/include/pj++/sock.hpp \
    pjproject-2.7.2/pjlib/include/pj++/string.hpp \
    pjproject-2.7.2/pjlib/include/pj++/timer.hpp \
    pjproject-2.7.2/pjlib/include/pj++/tree.hpp \
    pjproject-2.7.2/pjlib/include/pj++/types.hpp \
    pjproject-2.7.2/pjlib/include/pjlib++.hpp \
    pjproject-2.7.2/pjlib/include/pjlib.h \
    pjproject-2.7.2/pjlib/src/pj/ioqueue_common_abs.h \
    pjproject-2.7.2/pjlib/src/pj/os_symbian.h \
    pjproject-2.7.2/pjlib/src/pj/pool_signature.h \
    pjproject-2.7.2/pjlib/src/pj/sock_uwp.h \
    pjproject-2.7.2/pjlib/src/pjlib-test/rtems_network_config.h \
    pjproject-2.7.2/pjlib/src/pjlib-test/test.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/base64.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/cli.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/cli_console.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/cli_imp.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/cli_telnet.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/config.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/crc32.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/dns.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/dns_server.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/errno.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/getopt.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/hmac_md5.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/hmac_sha1.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/http_client.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/json.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/md5.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/pcap.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/resolver.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/scanner.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/scanner_cis_bitwise.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/scanner_cis_uint.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/sha1.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/srv_resolver.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/string.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/stun_simple.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/types.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util/xml.h \
    pjproject-2.7.2/pjlib-util/include/pjlib-util.h \
    pjproject-2.7.2/pjlib-util/src/pjlib-util-test/test.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/alaw_ulaw.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/audiodev.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/avi.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/avi_stream.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/bidirectional.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/circbuf.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/clock.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/codec.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/conference.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/config.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/config_auto.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/converter.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/delaybuf.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/doxygen.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/echo.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/echo_port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/endpoint.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/errno.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/event.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/format.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/frame.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/g711.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/jbuf.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/master_port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/mem_port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/null_port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/plc.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/resample.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/rtcp.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/rtcp_xr.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/rtp.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/sdp.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/sdp_neg.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/session.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/signatures.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/silencedet.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/sound.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/sound_port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/splitcomb.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/stereo.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/stream.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/stream_common.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/symbian_sound_aps.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/tonegen.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/transport.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/transport_adapter_sample.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/transport_ice.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/transport_loop.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/transport_srtp.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/transport_udp.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/types.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/vid_codec.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/vid_codec_util.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/vid_port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/vid_stream.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/vid_tee.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/videodev.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/wav_playlist.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/wav_port.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/wave.h \
    pjproject-2.7.2/pjmedia/include/pjmedia/wsola.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-audiodev/audiodev.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-audiodev/audiodev_imp.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-audiodev/audiotest.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-audiodev/config.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-audiodev/errno.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/amr_helper.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/amr_sdp_match.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/audio_codecs.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/bcg729.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/config.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/config_auto.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/ffmpeg_vid_codecs.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/g722.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/g7221.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/g7221_sdp_match.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/gsm.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/h263_packetizer.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/h264_packetizer.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/ilbc.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/ipp_codecs.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/l16.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/opencore_amr.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/openh264.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/opus.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/passthrough.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/silk.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/speex.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/types.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec/vid_toolbox.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-videodev/avi_dev.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-videodev/config.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-videodev/errno.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-videodev/opengl_dev.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-videodev/videodev.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-videodev/videodev_imp.h \
    pjproject-2.7.2/pjmedia/include/pjmedia-codec.h \
    pjproject-2.7.2/pjmedia/include/pjmedia.h \
    pjproject-2.7.2/pjmedia/include/pjmedia_audiodev.h \
    pjproject-2.7.2/pjmedia/include/pjmedia_videodev.h \
    pjproject-2.7.2/pjmedia/src/pjmedia/echo_internal.h \
    pjproject-2.7.2/pjmedia/src/pjmedia/ffmpeg_util.h \
    pjproject-2.7.2/pjmedia/src/pjmedia-audiodev/s60_g729_bitstream.h \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/g722/g722_dec.h \
    pjproject-2.7.2/pjmedia/src/pjmedia-codec/g722/g722_enc.h \
    pjproject-2.7.2/pjmedia/src/pjmedia-videodev/util.h \
    pjproject-2.7.2/pjmedia/src/test/test.h \
    pjproject-2.7.2/pjnath/docs/doc_ice.h \
    pjproject-2.7.2/pjnath/docs/doc_mainpage.h \
    pjproject-2.7.2/pjnath/docs/doc_nat.h \
    pjproject-2.7.2/pjnath/docs/doc_samples.h \
    pjproject-2.7.2/pjnath/docs/doc_stun.h \
    pjproject-2.7.2/pjnath/docs/doc_turn.h \
    pjproject-2.7.2/pjnath/include/pjnath/config.h \
    pjproject-2.7.2/pjnath/include/pjnath/errno.h \
    pjproject-2.7.2/pjnath/include/pjnath/ice_session.h \
    pjproject-2.7.2/pjnath/include/pjnath/ice_strans.h \
    pjproject-2.7.2/pjnath/include/pjnath/nat_detect.h \
    pjproject-2.7.2/pjnath/include/pjnath/stun_auth.h \
    pjproject-2.7.2/pjnath/include/pjnath/stun_config.h \
    pjproject-2.7.2/pjnath/include/pjnath/stun_msg.h \
    pjproject-2.7.2/pjnath/include/pjnath/stun_session.h \
    pjproject-2.7.2/pjnath/include/pjnath/stun_sock.h \
    pjproject-2.7.2/pjnath/include/pjnath/stun_transaction.h \
    pjproject-2.7.2/pjnath/include/pjnath/turn_session.h \
    pjproject-2.7.2/pjnath/include/pjnath/turn_sock.h \
    pjproject-2.7.2/pjnath/include/pjnath/types.h \
    pjproject-2.7.2/pjnath/include/pjnath.h \
    pjproject-2.7.2/pjnath/src/pjnath-test/server.h \
    pjproject-2.7.2/pjnath/src/pjnath-test/test.h \
    pjproject-2.7.2/pjnath/src/pjturn-srv/auth.h \
    pjproject-2.7.2/pjnath/src/pjturn-srv/turn.h \
    pjproject-2.7.2/pjsip/docs/doxygen.h \
    pjproject-2.7.2/pjsip/include/pjsip/print_util.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_auth.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_auth_aka.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_auth_msg.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_auth_parser.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_autoconf.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_config.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_dialog.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_endpoint.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_errno.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_event.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_module.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_msg.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_multipart.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_parser.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_private.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_resolve.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_tel_uri.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_transaction.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_transport.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_transport_loop.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_transport_tcp.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_transport_tls.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_transport_udp.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_types.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_ua_layer.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_uri.h \
    pjproject-2.7.2/pjsip/include/pjsip/sip_util.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/errno.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/evsub.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/evsub_msg.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/iscomposing.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/mwi.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/pidf.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/presence.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/publish.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/rpid.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/types.h \
    pjproject-2.7.2/pjsip/include/pjsip-simple/xpidf.h \
    pjproject-2.7.2/pjsip/include/pjsip-ua/sip_100rel.h \
    pjproject-2.7.2/pjsip/include/pjsip-ua/sip_inv.h \
    pjproject-2.7.2/pjsip/include/pjsip-ua/sip_regc.h \
    pjproject-2.7.2/pjsip/include/pjsip-ua/sip_replaces.h \
    pjproject-2.7.2/pjsip/include/pjsip-ua/sip_timer.h \
    pjproject-2.7.2/pjsip/include/pjsip-ua/sip_xfer.h \
    pjproject-2.7.2/pjsip/include/pjsua-lib/pjsua.h \
    pjproject-2.7.2/pjsip/include/pjsua-lib/pjsua_internal.h \
    pjproject-2.7.2/pjsip/include/pjsua2/account.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/call.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/config.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/doxygen.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/endpoint.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/json.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/media.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/persistent.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/presence.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/siptypes.hpp \
    pjproject-2.7.2/pjsip/include/pjsua2/types.hpp \
    pjproject-2.7.2/pjsip/include/pjsip.h \
    pjproject-2.7.2/pjsip/include/pjsip_auth.h \
    pjproject-2.7.2/pjsip/include/pjsip_simple.h \
    pjproject-2.7.2/pjsip/include/pjsip_ua.h \
    pjproject-2.7.2/pjsip/include/pjsua.h \
    pjproject-2.7.2/pjsip/include/pjsua2.hpp \
    pjproject-2.7.2/pjsip/src/pjsua2/util.hpp \
    pjproject-2.7.2/pjsip/src/test/test.h \
    pjproject-2.7.2/pjsip-apps/src/3rdparty_media_sample/config_site.h \
    pjproject-2.7.2/pjsip-apps/src/ipjsystest/Classes/ipjsystestAppDelegate.h \
    pjproject-2.7.2/pjsip-apps/src/ipjsystest/Classes/RootViewController.h \
    pjproject-2.7.2/pjsip-apps/src/ipjsystest/Classes/TestViewController.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/android/jni/pjsua_app_callback.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/bb10/src/applicationui.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/bb10/precompiled.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/ios/ipjsua/ipjsuaAppDelegate.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/ios/ipjsua/ipjsuaViewController.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/ios/ipjsua/Reachability.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/inc/pjsuaApplication.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/inc/pjsuaAppUi.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/inc/pjsuaContainer.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/inc/PjsuaContainerView.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/symbian/inc/pjsuaDocument.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/cli/comp/src/Globals.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/cli/comp/src/IPjsuaCallback.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/cli/comp/src/PjsuaCallback.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipBackEnd/ApiLock.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipBackEnd/MyApp.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipBackEnd/pch.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/gui.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app_common.h \
    pjproject-2.7.2/pjsip-apps/src/pjsua/pjsua_app_config.h \
    pjproject-2.7.2/pjsip-apps/src/pjsystest/gui.h \
    pjproject-2.7.2/pjsip-apps/src/pjsystest/resource.h \
    pjproject-2.7.2/pjsip-apps/src/pjsystest/systest.h \
    pjproject-2.7.2/pjsip-apps/src/py_pjsua/py_pjsua.h \
    pjproject-2.7.2/pjsip-apps/src/python/_pjsua.h \
    pjproject-2.7.2/pjsip-apps/src/samples/proxy.h \
    pjproject-2.7.2/pjsip-apps/src/samples/util.h \
    pjproject-2.7.2/pjsip-apps/src/vidgui/vidgui.h \
    pjproject-2.7.2/pjsip-apps/src/vidgui/vidwin.h \
    pjproject-2.7.2/third_party/BaseClasses/amfilter.h \
    pjproject-2.7.2/third_party/BaseClasses/combase.h \
    pjproject-2.7.2/third_party/BaseClasses/ctlutil.h \
    pjproject-2.7.2/third_party/BaseClasses/fourcc.h \
    pjproject-2.7.2/third_party/BaseClasses/measure.h \
    pjproject-2.7.2/third_party/BaseClasses/msgthrd.h \
    pjproject-2.7.2/third_party/BaseClasses/mtype.h \
    pjproject-2.7.2/third_party/BaseClasses/refclock.h \
    pjproject-2.7.2/third_party/BaseClasses/reftime.h \
    pjproject-2.7.2/third_party/BaseClasses/renbase.h \
    pjproject-2.7.2/third_party/BaseClasses/seekpt.h \
    pjproject-2.7.2/third_party/BaseClasses/streams.h \
    pjproject-2.7.2/third_party/BaseClasses/wxdebug.h \
    pjproject-2.7.2/third_party/BaseClasses/wxlist.h \
    pjproject-2.7.2/third_party/BaseClasses/wxutil.h \
    pjproject-2.7.2/third_party/bdsound/include/bdimad.h \
    pjproject-2.7.2/third_party/build/gsm/config.h \
    pjproject-2.7.2/third_party/build/resample/config.h \
    pjproject-2.7.2/third_party/build/speex/speex/speex_config_types.h \
    pjproject-2.7.2/third_party/build/speex/config.h \
    pjproject-2.7.2/third_party/build/srtp/config.h \
    pjproject-2.7.2/third_party/build/srtp/srtp_config.h \
    pjproject-2.7.2/third_party/g7221/common/basic_op.h \
    pjproject-2.7.2/third_party/g7221/common/basic_op_i.h \
    pjproject-2.7.2/third_party/g7221/common/config.h \
    pjproject-2.7.2/third_party/g7221/common/count.h \
    pjproject-2.7.2/third_party/g7221/common/defs.h \
    pjproject-2.7.2/third_party/g7221/common/huff_def.h \
    pjproject-2.7.2/third_party/g7221/common/huff_tab.h \
    pjproject-2.7.2/third_party/g7221/common/tables.h \
    pjproject-2.7.2/third_party/g7221/common/typedef.h \
    pjproject-2.7.2/third_party/g7221/decode/dct4_s.h \
    pjproject-2.7.2/third_party/g7221/encode/dct4_a.h \
    pjproject-2.7.2/third_party/gsm/inc/config.h \
    pjproject-2.7.2/third_party/gsm/inc/gsm.h \
    pjproject-2.7.2/third_party/gsm/inc/private.h \
    pjproject-2.7.2/third_party/gsm/inc/proto.h \
    pjproject-2.7.2/third_party/gsm/inc/toast.h \
    pjproject-2.7.2/third_party/gsm/inc/unproto.h \
    pjproject-2.7.2/third_party/gsm/tls/taste.h \
    pjproject-2.7.2/third_party/ilbc/anaFilter.h \
    pjproject-2.7.2/third_party/ilbc/constants.h \
    pjproject-2.7.2/third_party/ilbc/createCB.h \
    pjproject-2.7.2/third_party/ilbc/doCPLC.h \
    pjproject-2.7.2/third_party/ilbc/enhancer.h \
    pjproject-2.7.2/third_party/ilbc/filter.h \
    pjproject-2.7.2/third_party/ilbc/FrameClassify.h \
    pjproject-2.7.2/third_party/ilbc/gainquant.h \
    pjproject-2.7.2/third_party/ilbc/getCBvec.h \
    pjproject-2.7.2/third_party/ilbc/helpfun.h \
    pjproject-2.7.2/third_party/ilbc/hpInput.h \
    pjproject-2.7.2/third_party/ilbc/hpOutput.h \
    pjproject-2.7.2/third_party/ilbc/iCBConstruct.h \
    pjproject-2.7.2/third_party/ilbc/iCBSearch.h \
    pjproject-2.7.2/third_party/ilbc/iLBC_decode.h \
    pjproject-2.7.2/third_party/ilbc/iLBC_define.h \
    pjproject-2.7.2/third_party/ilbc/iLBC_encode.h \
    pjproject-2.7.2/third_party/ilbc/LPCdecode.h \
    pjproject-2.7.2/third_party/ilbc/LPCencode.h \
    pjproject-2.7.2/third_party/ilbc/lsf.h \
    pjproject-2.7.2/third_party/ilbc/packing.h \
    pjproject-2.7.2/third_party/ilbc/StateConstructW.h \
    pjproject-2.7.2/third_party/ilbc/StateSearchW.h \
    pjproject-2.7.2/third_party/ilbc/syntFilter.h \
    pjproject-2.7.2/third_party/milenage/milenage.h \
    pjproject-2.7.2/third_party/milenage/rijndael.h \
    pjproject-2.7.2/third_party/mp3/BladeMP3EncDLL.h \
    pjproject-2.7.2/third_party/mp3/mp3_port.h \
    pjproject-2.7.2/third_party/resample/include/resamplesubs.h \
    pjproject-2.7.2/third_party/resample/src/largefilter.h \
    pjproject-2.7.2/third_party/resample/src/resample.h \
    pjproject-2.7.2/third_party/resample/src/smallfilter.h \
    pjproject-2.7.2/third_party/resample/src/stddefs.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_bits.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_buffer.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_callbacks.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_echo.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_header.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_jitter.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_preprocess.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_resampler.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_stereo.h \
    pjproject-2.7.2/third_party/speex/include/speex/speex_types.h \
    pjproject-2.7.2/third_party/speex/libspeex/_kiss_fft_guts.h \
    pjproject-2.7.2/third_party/speex/libspeex/arch.h \
    pjproject-2.7.2/third_party/speex/libspeex/cb_search.h \
    pjproject-2.7.2/third_party/speex/libspeex/cb_search_arm4.h \
    pjproject-2.7.2/third_party/speex/libspeex/cb_search_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/cb_search_sse.h \
    pjproject-2.7.2/third_party/speex/libspeex/fftwrap.h \
    pjproject-2.7.2/third_party/speex/libspeex/filterbank.h \
    pjproject-2.7.2/third_party/speex/libspeex/filters.h \
    pjproject-2.7.2/third_party/speex/libspeex/filters_arm4.h \
    pjproject-2.7.2/third_party/speex/libspeex/filters_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/filters_sse.h \
    pjproject-2.7.2/third_party/speex/libspeex/fixed_arm4.h \
    pjproject-2.7.2/third_party/speex/libspeex/fixed_arm5e.h \
    pjproject-2.7.2/third_party/speex/libspeex/fixed_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/fixed_debug.h \
    pjproject-2.7.2/third_party/speex/libspeex/fixed_generic.h \
    pjproject-2.7.2/third_party/speex/libspeex/kiss_fft.h \
    pjproject-2.7.2/third_party/speex/libspeex/kiss_fftr.h \
    pjproject-2.7.2/third_party/speex/libspeex/lpc.h \
    pjproject-2.7.2/third_party/speex/libspeex/lpc_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/lsp.h \
    pjproject-2.7.2/third_party/speex/libspeex/lsp_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/ltp.h \
    pjproject-2.7.2/third_party/speex/libspeex/ltp_arm4.h \
    pjproject-2.7.2/third_party/speex/libspeex/ltp_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/ltp_sse.h \
    pjproject-2.7.2/third_party/speex/libspeex/math_approx.h \
    pjproject-2.7.2/third_party/speex/libspeex/misc_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/modes.h \
    pjproject-2.7.2/third_party/speex/libspeex/nb_celp.h \
    pjproject-2.7.2/third_party/speex/libspeex/os_support.h \
    pjproject-2.7.2/third_party/speex/libspeex/pseudofloat.h \
    pjproject-2.7.2/third_party/speex/libspeex/quant_lsp.h \
    pjproject-2.7.2/third_party/speex/libspeex/quant_lsp_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/resample_sse.h \
    pjproject-2.7.2/third_party/speex/libspeex/sb_celp.h \
    pjproject-2.7.2/third_party/speex/libspeex/smallft.h \
    pjproject-2.7.2/third_party/speex/libspeex/stack_alloc.h \
    pjproject-2.7.2/third_party/speex/libspeex/vbr.h \
    pjproject-2.7.2/third_party/speex/libspeex/vorbis_psy.h \
    pjproject-2.7.2/third_party/speex/libspeex/vq.h \
    pjproject-2.7.2/third_party/speex/libspeex/vq_arm4.h \
    pjproject-2.7.2/third_party/speex/libspeex/vq_bfin.h \
    pjproject-2.7.2/third_party/speex/libspeex/vq_sse.h \
    pjproject-2.7.2/third_party/speex/symbian/config.h \
    pjproject-2.7.2/third_party/speex/win32/config.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/aes.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/aes_gcm_ossl.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/aes_icm.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/aes_icm_ossl.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/alloc.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/auth.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/cipher.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/crypto_kernel.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/crypto_types.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/datatypes.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/err.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/hmac.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/integers.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/key.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/null_auth.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/null_cipher.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/rdb.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/rdbx.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/sha1.h \
    pjproject-2.7.2/third_party/srtp/crypto/include/stat.h \
    pjproject-2.7.2/third_party/srtp/include/ekt.h \
    pjproject-2.7.2/third_party/srtp/include/getopt_s.h \
    pjproject-2.7.2/third_party/srtp/include/srtp.h \
    pjproject-2.7.2/third_party/srtp/include/srtp_priv.h \
    pjproject-2.7.2/third_party/srtp/include/ut_sim.h \
    pjproject-2.7.2/third_party/threademulation/include/ThreadEmulation.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/include/real_fft.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/include/signal_processing_library.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/include/spl_inl.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/include/spl_inl_armv7.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/include/spl_inl_mips.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/complex_fft_tables.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/signal_processing/resample_by_2_internal.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/fft4g.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/ring_buffer.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/common_audio/wav_file.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/include/echo_cancellation.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_common.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_core.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_core_internal.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_rdft.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/aec_resampler.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aec/echo_cancellation_internal.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/include/echo_control_mobile.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/aecm_core.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/aecm/aecm_defines.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/logging/aec_logging.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/logging/aec_logging_file_handling.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/include/noise_suppression.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/include/noise_suppression_x.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/defines.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/ns_core.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/nsx_core.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/nsx_defines.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/ns/windows_private.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/utility/delay_estimator.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/utility/delay_estimator_internal.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/modules/audio_processing/utility/delay_estimator_wrapper.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/system_wrappers/interface/compile_assert_c.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/system_wrappers/interface/cpu_features_wrapper.h \
    pjproject-2.7.2/third_party/webrtc/src/webrtc/typedefs.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/basic_types.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/compare.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/compare_row.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/convert.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/convert_argb.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/convert_from.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/convert_from_argb.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/cpu_id.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/macros_msa.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/mjpeg_decoder.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/planar_functions.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/rotate.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/rotate_argb.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/rotate_row.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/row.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/scale.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/scale_argb.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/scale_row.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/version.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv/video_common.h \
    pjproject-2.7.2/third_party/yuv/include/libyuv.h

