#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_HAS_FFMPEG 0
#define PJMEDIA_VIDEO_DEV_HAS_SDL 0
#define PJMEDIA_VIDEO_DEV_HAS_FFMPEG 0
#define PJMEDIA_VIDEO_DEV_HAS_V4L2 0
#define PJMEDIA_HAS_FFMPEG_CODEC 0
#define PJMEDIA_HAS_LIBSWSCALE 0
#define PJMEDIA_HAS_LIBAVFORMAT 0
